version: "0.1"
environments:
  - name: develop
    branch: develop
    mode: pull-request
apps:
  - name: react-notes
    path: ""
    text-resources:
      - path: "*.json"
        format: flat-key-value
